/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as SuperSplatRouteImport } from './routes/super.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/super/',
  path: '/super/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperSplatRoute = SuperSplatRouteImport.update({
  id: '/super/$',
  path: '/super/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/admin/$': typeof AdminSplatRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/super/$': typeof SuperSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/admin/$': typeof AdminSplatRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/super/$': typeof SuperSplatRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/admin/$': typeof AdminSplatRoute
  '/menu/$slug': typeof MenuSlugRoute
  '/super/$': typeof SuperSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview'
    | '/admin/$'
    | '/menu/$slug'
    | '/super/$'
    | '/admin/'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/admin/$'
    | '/menu/$slug'
    | '/super/$'
    | '/admin'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/preview'
    | '/admin/$'
    | '/menu/$slug'
    | '/super/$'
    | '/admin/'
    | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewRoute: typeof PreviewRoute
  AdminSplatRoute: typeof AdminSplatRoute
  MenuSlugRoute: typeof MenuSlugRoute
  SuperSplatRoute: typeof SuperSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/super'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/$': {
      id: '/super/$'
      path: '/super/$'
      fullPath: '/super/$'
      preLoaderRoute: typeof SuperSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewRoute: PreviewRoute,
  AdminSplatRoute: AdminSplatRoute,
  MenuSlugRoute: MenuSlugRoute,
  SuperSplatRoute: SuperSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  SuperIndexRoute: SuperIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
